### ISSUE TITLE
TOC settings with tabs are not recognised

### ISSUE THREAD

**Issue by notakoder** [iridescent-dev/pico-toc-plugin#11]
TOC setting in YAML header is not recognised if it tabs are used instead of spaces. For instance,

```
TOC:
    heading: Table of contents
    min_headers: 4
```
Does not work. But the same code written with spaces works.

```
TOC:
    heading: Table of contents
    min_headers: 4
```
Is there any particular reason to this design?

**Comment by dkyme** [comment]
`Tabs have been outlawed since they are treated differently by different editors and tools. And since indentation is so critical to proper interpretation of YAML, this issue is just too tricky to even attempt.`
Source: http://yaml.org/faq.html

**Comment by notakoder** [comment]
Thank you for the explanation.
