### ISSUE TITLE
Starting from `h2` instead of `h1`

### ISSUE THREAD

**Issue by notakoder** [iridescent-dev/pico-toc-plugin#5]
How do I make the plugin to start considering from `h2` instead of `h1`, which is my title and must be avoided in the table of contents?

**Comment by iridescent-dev** [comment]
Hi,

I had not foreseen this scenario, but now it is done!
I added a `toc_min_level` option which allows to indicate the minimum header level to display.

Thanks for your help!

**Comment by notakoder** [comment]
How about making it a bit more powerful by adding and option for ordered lists too? Currently I have modified line# 103 to show the following.

`$ul_element = $document->createElement('ol');`

**Comment by notakoder** [comment]
That's nice. Thank you. Adding an option for ordered lists would also fix the semantic incorrectness of the listing the headings in the TOC. Ideally each heading must be nested under it's parent heading, like this:
```
h2
  h3
    h4
  h3
h2
```
Currently, the semantic rendering to list headings  is not correct. Instead of a nested `<li>` the plugin using non-nested `<li>` tags to display nested headings, and using CSS, they are indented to achieve visual correctness. While this works for unordered lists, for ordered lists, the TOC numbering is continuous even for nested headings.

I hope it's alright giving such improvement feedback that adds a lot of work. I am not a coder myself, else I would have contributed. These are the only ways (feedback for improvements) I can contribute.

**Comment by iridescent-dev** [comment]
No problem, all feedbacks are welcome! Thank you for suggesting and detailing this improvement.

The last 2 weeks I was working on another Pico plugin, but this week I was able to work on it.

I added a "style" attribute which can be "numbers", "bullets" or "none". It's committed on the [develop branch](https://github.com/iridescent-dev/pico-toc-plugin/tree/develop) and I'm interested to have your feedback before releasing it as a new version.

**Comment by notakoder** [comment]
That's great to see the changes. Nested numbered lists are displayed correctly. Good job. But I don't understand the concept of `none` as a style. Semantically we only have two types of lists: `ol` and `ul` (bulleted and numbered) and I guess your code reflects that too.

1. Setting the style to `none` lists the headings with the bullets itself.
2. The code in line# 179 (assuming I understood it correctly) says `$list_element = $document->createElement($style === "numbers" ? 'ol' : 'ul');`, meaning if variable `style` equals `numbers`, then render with `ol`, else with `ul`.

So here's my suggestion. The default should be `ol` (numbers) because that is the norm not just on the Internet but in books too because numbered lists makes the TOC more navigation friendly. Then, changing `ol` to `ul` must be the done manually either in the global config file or individual file.

**Comment by iridescent-dev** [comment]
I hesitated to offer an option to choose `ol` or `ul`, but preferred to offer to choose the CSS style:
- `none` I add nothing
- `bullets` I prefix headings with •
- `numbers` I prefix headings with 1.1, 1.2, ...

I changed to an `<ol>` for the numbers style and kept `<ul>` otherwise, but I just read [this text](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol) which made me change my mind:

> The `<ol>` and `<ul>` elements both represent a list of items. The difference is with the `<ol>` element, the order is meaningful. For example: 
> Steps in a recipe
> Turn-by-turn directions
> The list of ingredients in decreasing proportion on nutrition information labels
>
> To determine which list to use, try changing the order of the list items; if the meaning changes, use the `<ol>` element — otherwise you can use `<ul>`.

The tables of contents are necessarily ordered, so I just changed to keep only `<ol>`. There is no more `<ul>`.

For the default option I chose `none` to not change the default behavior of the current version of the plugin.

Looks like I've strayed a bit from the original request but at least there are the nested lists 😅

**Comment by notakoder** [comment]
To add to Mozilla's explanation, TOCs, more than just being an ordered list, also conveys the outline of the document/book. The literary size of the content, and how to plan to read it... all can be decided from just the TOC. I always prefer to use ordered lists for TOC, which is why I suggested the same [long back](https://github.com/iridescent-dev/pico-toc-plugin/issues/5#issuecomment-944190030) and I am thankful you considered it. But I am not sure if the decision to ignore unordered lists from TOC was a good idea. Let me tell you why and try to convince you to add it back. :smile: 

This I say from the perspective of a product designer. A lot of people do not use a particular feature exactly the way it is intended to; sometimes out of stupidity, and other times out of creativity. Writers are creative souls and creativity strikes us in various ways. The possibility of a document that does not just require but also demands an unordered toc, is not just possible but also plausible. So when we develop and release a product, it is a nice idea to make it a little flexible as opposed to being super rigid, so that it accommodates various possibilities so long as it is relevant to the idea of TOC.

Anyway, nice work so far. Looking forward to the final release.

**Comment by iridescent-dev** [comment]
I'm not sure it's appropriate to suggest using an `<ul>`, TOC displays the headers in order of appearance on the page, just for that it is necessarily an ordered list.

But I'm not here to stop creativity and it wasn't much to do, so I added an option to choose the tag used.

New release is available. Thanks again for your contribution!

**Comment by notakoder** [comment]
> I'm not sure it's appropriate to suggest using an `<ul>`, TOC displays the headers in order of appearance on the page, just for that it is necessarily an ordered list.

And I agree with you. Just that there are designers who choose to simply bullet the TOC, and other who choose to just list it. So a bit of flexibility, that's all.

Thank you to you too.
